#!/usr/bin/env python3
"""
Scout graph builder — Phase 1 of the concept-graph roadmap.

Reads the concept registry (index/concepts*.json) and segments
(index/segments.json) and emits index/concept-graph.json: deterministic
co-occurrence edges between concepts that share evidence segments.
No model, no network — Python standard library only.

Anchor contract (see docs/graph-roadmap.md): every edge carries
segment-anchored evidence with its validity context:

    {
      "from": "...", "to": "...", "type": "co_occurs",
      "weight": <shared segment count>,
      "cross_workspace": true|false,
      "evidence": [
        {"segment": "<segment_id>", "from_offset": 0,
         "to_offset": <segment line span - 1>,
         "source_hash": "<hash of the segment's source file>"}
      ],
      "quote": "<segment title(s)> — recovery key",
      "date": "<earliest source_date among shared segments>"
    }

Hashes are copied from segments.json's `source_hashes` when the pipeline
recorded them (CC-2A-R); otherwise computed here as sha256 over the source
file bytes, prefixed "sha256:". Readers should treat a hash mismatch as a
stale anchor (detect-and-regenerate world: re-run this script).

Safety: refuses to overwrite a concept-graph.json it did not generate
(hand-curated graphs stay safe). Pass --force to replace anyway.

Usage:
    python3 scripts/build-graph.py --dossier-root "$DOSSIER_ROOT"
    python3 scripts/build-graph.py --dossier-root "$DOSSIER_ROOT" --min-shared 2

No external dependencies (Python standard library only).
"""

import argparse
import hashlib
import itertools
import json
from datetime import datetime, timezone
from pathlib import Path


GENERATED_BY = "scout scripts/build-graph.py"


def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"[warn] could not read {path}: {e}")
        return None


def as_array(raw, key):
    """Tolerant envelope handling: accept {key: [...]} or a bare array."""
    if raw is None:
        return []
    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict) and isinstance(raw.get(key), list):
        return raw[key]
    return []


def load_concepts(index_dir):
    """Merge concepts*.json the same way the reader does (sorted glob,
    last-writer-wins on concept_id)."""
    merged = {}
    for path in sorted(index_dir.glob("concepts*.json")):
        for c in as_array(load_json(path), "concepts"):
            cid = c.get("concept_id")
            if cid:
                merged[cid] = c
    return list(merged.values())


def sha256_of(path):
    h = hashlib.sha256()
    try:
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
    except OSError:
        return None
    return "sha256:" + h.hexdigest()


def build_graph(dossier_root, min_shared, force=False):
    root = Path(dossier_root).expanduser().resolve()
    index_dir = root / "index"
    out_path = index_dir / "concept-graph.json"

    seg_raw = load_json(index_dir / "segments.json")
    segments = as_array(seg_raw, "segments")
    concepts = load_concepts(index_dir)
    if not concepts:
        print(f"[error] no concepts found in {index_dir}/concepts*.json — nothing to connect.")
        print("        (Concepts come from hand-curation or scripts/extract-concepts.py.)")
        return 1
    if not segments:
        print(f"[error] no segments in {index_dir}/segments.json. Run segment.py first.")
        return 1

    # Guard: never silently replace a graph this script did not generate.
    if out_path.exists() and not force:
        existing = load_json(out_path)
        if existing is not None and existing.get("generated_by") != GENERATED_BY:
            print(f"[error] {out_path.relative_to(root)} exists and was not generated by")
            print(f"        this script — it may contain hand-curated or extracted edges")
            print(f"        that this run would REPLACE entirely. Re-run with --force")
            print(f"        if you are sure. (Extracted graphs belong to extract-concepts.py.)")
            return 1

    seg_by_id = {s.get("segment_id"): s for s in segments if s.get("segment_id")}

    # Source hashes: prefer the pipeline's own record (CC-2A-R), else compute.
    source_hashes = {}
    if isinstance(seg_raw, dict) and isinstance(seg_raw.get("source_hashes"), dict):
        source_hashes.update(seg_raw["source_hashes"])
    files_raw = load_json(index_dir / "master-index.json")
    path_by_file = {
        f.get("file_id"): f.get("path")
        for f in as_array(files_raw, "files")
        if f.get("file_id")
    }

    def hash_for(file_id):
        if file_id in source_hashes:
            return source_hashes[file_id]
        rel = path_by_file.get(file_id)
        if rel:
            h = sha256_of(root / rel)
            if h:
                source_hashes[file_id] = h
                return h
        return None

    # Concepts per segment.
    concepts_by_segment = {}
    for c in concepts:
        for sid in c.get("source_segments") or []:
            if sid in seg_by_id:
                concepts_by_segment.setdefault(sid, []).append(c["concept_id"])

    ws_of = {c["concept_id"]: c.get("primary_workspace") for c in concepts}

    def evidence_for(sid):
        seg = seg_by_id[sid]
        span = 0
        if isinstance(seg.get("start_line"), int) and isinstance(seg.get("end_line"), int):
            span = max(0, seg["end_line"] - seg["start_line"])
        ev = {"segment": sid, "from_offset": 0, "to_offset": span}
        h = hash_for(seg.get("file_id"))
        if h:
            ev["source_hash"] = h
        return ev

    pairs = {}
    for sid, cids in concepts_by_segment.items():
        for a, b in itertools.combinations(sorted(set(cids)), 2):
            pairs.setdefault((a, b), []).append(sid)

    edges = []
    skipped = 0
    for (a, b), shared in sorted(pairs.items()):
        if len(shared) < min_shared:
            skipped += 1
            continue
        shared = sorted(shared)
        titles = [seg_by_id[s].get("title") or s for s in shared]
        dates = [seg_by_id[s].get("source_date") for s in shared]
        dates = sorted(d for d in dates if d)
        edges.append({
            "from": a,
            "to": b,
            "type": "co_occurs",
            "weight": len(shared),
            "cross_workspace": bool(ws_of.get(a) and ws_of.get(b) and ws_of[a] != ws_of[b]),
            "evidence": [evidence_for(s) for s in shared],
            "quote": " · ".join(titles)[:220],
            **({"date": dates[0]} if dates else {}),
        })

    output = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generated_by": GENERATED_BY,
        "min_shared": min_shared,
        "hash_algo_note": "source_hash copied from segments.json source_hashes when present, else sha256 of source file bytes",
        "total_edges": len(edges),
        "edges": edges,
    }
    index_dir.mkdir(exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

    cross = sum(1 for e in edges if e["cross_workspace"])
    print(f"[built] {out_path.relative_to(root)}")
    print(f"        {len(edges)} co-occurrence edge(s) over {len(concepts)} concepts"
          f" ({cross} cross-workspace)"
          + (f", {skipped} pair(s) below --min-shared {min_shared}" if skipped else ""))
    isolated = [c["concept_id"] for c in concepts
                if not any(c["concept_id"] in (e["from"], e["to"]) for e in edges)]
    if isolated:
        print(f"[note]  {len(isolated)} concept(s) have no edges (orphans): "
              + ", ".join(isolated[:6]) + ("…" if len(isolated) > 6 else ""))
    print(f"\nNext: restart Scout to see related concepts, or run")
    print(f"      python3 scripts/scout-to-metta.py --dossier-root <root>  for the AtomSpace export.")
    return 0


def main():
    p = argparse.ArgumentParser(description="Build concept-graph.json from shared evidence segments.")
    p.add_argument("--dossier-root", default=".", help="Path to dossier root containing index/")
    p.add_argument("--min-shared", type=int, default=1,
                   help="Minimum shared segments for an edge (default 1; use 2+ for auto-extracted concepts)")
    p.add_argument("--force", action="store_true",
                   help="Overwrite a concept-graph.json not generated by this script")
    args = p.parse_args()
    if not str(args.dossier_root or "").strip():
        print("[error] --dossier-root is empty. Set $DOSSIER_ROOT first.")
        return 1
    return build_graph(args.dossier_root, args.min_shared, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
